name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./nginx/
          push: true
          tags: vcatconsulting/symfony-nginx:latest
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./php/7.3-fpm/
          push: true
          tags: vcatconsulting/symfony-php:7.3-fpm
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./php/7.4-fpm/
          push: true
          tags: vcatconsulting/symfony-php:7.4-fpm
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./php/8.0-fpm/
          push: true
          tags: vcatconsulting/symfony-php:8.0-fpm
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./php/8.0-fpm-xdebug/
          push: true
          tags: vcatconsulting/symfony-php:8.0-fpm-xdebug
